BooksAttendee/urls.py
from django.urls import path
from . import views

app_name = 'BooksAttendee'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:book_id>/', views.detail, name='detail'),
    path('<int:book_id>/update/', views.update, name='update'),
    path('<int:book_id>/delete/', views.delete, name='delete'),
]

BooksManager/urls.py
from django.contrib import admin
from django.urls import path, include
from BooksAttendee import viewsets
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'books', viewsets.BookViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('books/', include('BooksAttendee.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

BooksAttendee/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

BooksAttendee/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from BooksAttendee.models import Book

# Create your views here.
def index(request):
    books_list = Book.objects.order_by('-created_at')
    context = {'books_list': books_list}
    return render(request, 'BooksAttendee/index.html', context)

def create(request):
    if request.method == 'GET':
        return render(request, 'BooksAttendee/create.html')
    elif request.method == 'POST':
        book = Book(title=request.POST['title'], description=request.POST['description'])
        book.save()
        return HttpResponseRedirect(reverse('BooksAttendee:index'))

def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'BooksAttendee/detail.html', {'book': book})

def update(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.title = request.POST['title']
    book.description = request.POST['description']
    book.save()
    return HttpResponseRedirect(reverse('BooksAttendee:detail', args=(book.id,)))

def delete(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return HttpResponseRedirect(reverse('BooksAttendee:index'))

BooksAttendee/templates/BooksAttendee/create.html
<h2>Crear</h2>
<form action="{% url 'BooksAttendee:create' %}" method="post">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="title">Titulo: </label>
    <input type="text" name="title" id="title"><br>
    <label for="decription">Descripcion: </label>
    <input type="text" name="description" id="description"><br>
    <input type="submit" value="Guardar">
</form>

BooksAttendee/templates/BooksAttendee/detail.html
<h2>Editar</h2>
<form action="{% url 'BooksAttendee:update' book.id %}" method="post">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="title">Titulo: </label>
    <input type="text" name="title" id="title" value="{{ book.title }}"><br>
    <label for="decription">Descripcion: </label>
    <input type="text" name="description" id="description" value="{{ book.description }}"><br>
    <input type="submit" value="Guardar">
</form>
<a href="{% url 'BooksAttendee:delete' book.id %}">Eliminar</a>

BooksAttendee/templates/BooksAttendee/index.html
{% if books_list %}
    <ul>
    {% for book in books_list %}
        <li><a href="{% url 'BooksAttendee:detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}
<a href="{% url 'BooksAttendee:create' %}">Crear un nuevo libro</a>